version: 0.2

phases: 
    install:
       commands:
            - echo installing webserver
            - sudo apt update
            - sudo apt install apache2
            
build:
       commands:
            - echo building file
            - cp index.html /var/www/html/
            
post build:
       commands:
            -echo configured
            
artifacts:
       files:
            - "**/*"
            
